# Generated by Django 5.2 on 2025-04-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),  
                ('kategori', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=100)),
            ],
        ),
    ]
